### ISSUE TITLE
Ошибка.

### ISSUE THREAD

**Issue by ghost** [k-egor-smirnov/detour#6]
An internal error occured while attempting to perform this command при вызове команды /detour list

**Comment by ghost** [comment]
Права на эту команду выданы.

**Comment by ghost** [comment]
Лог консоли при вызове этой команды:

`[04:51:14] [Server thread/WARN]: Unexpected exception while parsing console command "detour list"
org.bukkit.command.CommandException: Unhandled exception executing command 'detour' in plugin Detour v1.4.2
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[server.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[server.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:707) ~[server.jar:git-Spigot-8043ebc-dd99c5b]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:692) [server.jar:git-Spigot-8043ebc-dd99c5b]
	at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:433) [server.jar:git-Spigot-8043ebc-dd99c5b]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:397) [server.jar:git-Spigot-8043ebc-dd99c5b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:956) [server.jar:git-Spigot-8043ebc-dd99c5b]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [server.jar:git-Spigot-8043ebc-dd99c5b]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: java.lang.NullPointerException
	at ru.alphach1337.detour.commands.List.execute(List.java:66) ~[?:?]
	at ru.alphach1337.detour.commands.CommandHandler.onCommand(CommandHandler.java:30) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[server.jar:git-Spigot-8043ebc-dd99c5b]
	... 8 more`
